### ISSUE TITLE
Unable to return token

### ISSUE THREAD

**Issue by iHaagcom** [mattfeltonma/azuregraphpython#2]
makeapirequest(endpoint,token,q_param=None)
NameError: name 'token' is not defined. Did you mean: 'open'?

**Comment by mattfeltonma** [comment]
Hi there. I haven't touched this code in about 3 years, so some of the libraries may be out of date. Looking back at the code, likely you are failing to obtain a token.

**Comment by iHaagcom** [comment]
Does this still run for you now if you try it?

**Comment by iHaagcom** [comment]
That is correct. I can authenticate with:


`credentials = (my_client_id, my_client_secret)`
`account = Account(credentials, auth_flow_type='credentials', tenant_id=my_tenantid)`
`if account.authenticate():`
 `print('Authenticated!')`
 and
 
`auth = f'https://login.microsoftonline.com/{tenant_id}`
`app = msal.ConfidentialClientApplication(`
    `client_id, authority=auth, client_credential=client_secret)`
`result = app.acquire_token_for_client(scopes=['https://graph.microsoft.com/.default'])`

`token = result['access_token']`
 
 But unable to phase for the logs now when calling the makeapirequest function:

'Authorization':'Bearer {0}'.format(token['accessToken'])}
TypeError: string indices must be integers

**Comment by mattfeltonma** [comment]
Hi there. That error looks to indicate that token has no value and thus it can't call on the property. Your best bet would be to step through the code to see at which point it is failing. Unfortunately, I don't do much with the Graph API these days. You might be better off finding another example.

**Comment by iHaagcom** [comment]
`def show_signin():`
`# Graph^0`
`request_headers = msgraph_auth()`
`results = msgraph_request`
`(graph_url + /v1.0/auditLogs/signIns', request_headers)`
`if results:`
`print (results)`

Trace back:

New access token retrieved...
{'error': {'code': 'Authentication_RequestFromNonPremiumTenantOrB2CTenant '
doesn't have premium license"
"innerError': {'date' :
2022-03-08T13:57:13

Either, I need to add dates to the headers for the request or Microsoft have locked it down now with the licensing model?

**Comment by mattfeltonma** [comment]
Ahh yes, looks like a licensing issue. What are you trying to grab?

Matt Felton
________________________________

**Comment by iHaagcom** [comment]
The same as what you wrote about on your blog about Audit and Signin logs for Azure/Office365 (even compliance logs), storing them eliminating the limited 7 day limitation (as csv or json for now)

**Comment by mattfeltonma** [comment]
Looks like that API is now only accessible with a P1 license (https://docs.microsoft.com/en-us/azure/active-directory/reports-monitoring/howto-configure-prerequisites-for-reporting-api). That aligns with the error you're seeing.

There is a GitHub issue in the public documentation with the same error you have listed (https://github.com/MicrosoftDocs/azure-docs/issues/51693).

**Comment by mattfeltonma** [comment]
Updated the README for the code to note P1 or above is required. Thanks for pointing this out!
